### PR TITLE
Mount common volume for an application as read-only data volume

### PR DESCRIPTION
**Pull request by kitchoi**
Mount a common data volume on the host machine to the container based on information given by the database.
Since we don't yet have a database, two namedtuples (Application and Volume) are coded here, and are to be placed by ORM objects.

Note: For docker version >= 1.11, mounting a host directory that does not exist will no longer create the directory (I was surprised to find out that it does for docker version < 1.11).  To be sure, we should always check if the source path exists.

I would prefer refactoring the path existence check to the ContainerManager._start_container in a separate PR.

### CODE REVIEW

**Comment by itziakos** [comment]
:+1:

**Comment by kitchoi** [comment]
Thanks!

**Comment by kitchoi** [comment]
Note that the host directory needs to have a read-execute permission for `others` for this works with the current docker images.

**Comment by itziakos** [comment]
> Note that the host directory needs to have a read-execute permission for others for this works with the current docker images.

Yes, it is assumed that the admin has setup the folders with the right permissions.

**Pull request merged**
