### PR TITLE
Rename srdata configurable class tag to startupdata

### LINKED ISSUE #563: Rename `srdata` configurable class tag for consistency
The `srdata` tag used in the `StartupData` configurable should be renamed to `startupdata`, for better consistency and easier debug.

### PR DESCRIPTION
**Pull request by robertopreste**
Closes #563

### CODE REVIEW

**Review by flongford — COMMENTED** [review]
Nit: I found one remaining `srdata` in the documentation:
https://github.com/simphony/simphony-remote/blob/563-rename-srdata-tag/doc/source/developer/docker.rst

**Comment by robertopreste** [comment]
> Nit: I found one remaining `srdata` in the documentation:
> https://github.com/simphony/simphony-remote/blob/563-rename-srdata-tag/doc/source/developer/docker.rst

Right, thanks for spotting this!

**Review by flongford — APPROVED** [review]
LGTM! I guess the last change will need to be to the Paraview-SR repo?

**Comment by robertopreste** [comment]
> LGTM! I guess the last change will need to be to the Paraview-SR repo?

Exactly, I've already opened a merge request there.

**Pull request merged**
