### PR TITLE
Rename url to urlpath where it is possible and appropriate

### PR DESCRIPTION
**Pull request by kitchoi**
For #54

### CODE REVIEW

**Comment by kitchoi** [comment]
For #54

**Comment by kitchoi** [comment]
Will have a small merge conflict with #90

**Comment by stefanoborini** [comment]
That's a good step in the right direction, but I am also concerned about internal uses. in some places, we might use one instead of the other.

**Comment by stefanoborini** [comment]
@kitchoi I merge this, so I can bring your changes into the REST.

**Pull request merged**
