### PR TITLE
Fix close button issue

### LINKED ISSUE #479: Stop application can be clicked and triggers red dot status indicator
If you click on the "stop application" entry in the menu, even if it's disabled, it still triggers something, because the red dot indicator starts flashing as if the application is being turned off.

### PR DESCRIPTION
**Pull request by martinRenou**
As it's not a "button" element but a "li" element, there is no disable attribute, we only play with the disabled class which change the visual aspect but doesn't prevent the click event to be triggered.

I fixed this by changing the `disabled` class which now prevents the mouse events. 

Closes #479

### CODE REVIEW

**Comment by stefanoborini** [comment]
The solution is good, but I was wondering if we can actually prevent the click. Just curious.

**Comment by martinRenou** [comment]
I changed it, it now prevents the click

**Comment by stefanoborini** [comment]
No, leave the check. It makes sense it's there. You can't operate if it's not running, but it should also prevent the click.

**Comment by martinRenou** [comment]
Ok, so I should do the same for "StartApplication" and add a check in order to stay consistent

**Comment by stefanoborini** [comment]
Please add a test that the thing is actually not starting or stopping when those conditions happen.

**Pull request merged**
