### PR TITLE
Activates venv at start

### PR DESCRIPTION
**Pull request by stefanoborini**
Prevents running without venv activated. Just a courtesy.

### CODE REVIEW

**Comment by kitchoi** [comment]
I don't think this is necessary... for example, the user's virtual environment may not be called `venv`

**Comment by stefanoborini** [comment]
we create it as such in the makefile. @kitchoi

**Comment by kitchoi** [comment]
IMHO the start script is in fact not needed, to keep the directory slim.  If we need to provide such shortcut and that shortcut has to be consistent with the Makefile, a 'start' target can be provided inside the Makefile.  Outside of it, the script should be general.  Alternatively we can update the deployment documentation.

**Comment by kitchoi** [comment]
I don't have a strong opinion afterall.  I personally don't use this script.

**Comment by kitchoi** [comment]
@sbo will this break the travis's yaml in #150?

**Pull request closed without merging**
