### PR TITLE
Enhanced remoteappdb

### PR DESCRIPTION
**Pull request by stefanoborini**
Provides an enhanced version of the remoteappdb that allows removal of users and apps, and better error report.

### CODE REVIEW

**Comment by kitchoi** [comment]
Reference #28

**Comment by kitchoi** [comment]
Testing the utility manually, I notice there is a retrogression in assigning the volume_mode.  The `volume_mode` is always `None` (not just displayed as None but actually None in the database).

```
(simremote)kit@kit-virtual-machine:simphony-remote$ remoteappdb --db=testing.db app grant simphonyproject/empty-ubuntu tester --allow-home --volume /appdata/image_name/common:/appdata:ro
(simremote)kit@kit-virtual-machine:simphony-remote$ remoteappdb --db=testing.db user list --show-apps
ID    Name    App                             Home    View    Common  Vol. Source                 Vol. Target      Vol. Mode
----  ------  ----------------------------  ------  ------  --------  --------------------------  -------------  -----------
1     kit     simphonyproject/empty-ubuntu       1       1         0
              simphonyproject/empty-ubuntu       1       0         1  /appdata/image_name/common  /appdata
2     tester  simphonyproject/empty-ubuntu       1       0         1  /appdata/image_name/common  /appdata
```

**Comment by kitchoi** [comment]
Regarding cascading delete, this might be useful? (if you've tried and it doesn't work, please ignore)
http://docs.sqlalchemy.org/en/latest/orm/cascades.html#delete

**Comment by kitchoi** [comment]
Regarding the cascading delete reference, that also requires changes in the orm itself. We might want to do that in a separate PR if we want to go for it.

**Comment by stefanoborini** [comment]
We can't do cascading delete. sqlite does not support it.

**Comment by kitchoi** [comment]
> We can't do cascading delete. sqlite does not support it.

Okay.  Thanks for checking.

**Comment by stefanoborini** [comment]
I need to revise my statement. sqlite does support it, but it needs to be enabled, and it's not by default. That's why it didn't work when I tried. I'll have to study a bit on this regard and as you said, change the model.

**Comment by kitchoi** [comment]
LGTM

**Pull request merged**
