### PR TITLE
Rework api reference in documentation

### PR DESCRIPTION
**Pull request by itziakos**
This PR changes the way the api reference is autogenerated and rendered.

- The reference documentation is now autogenerated when `make html` is used and make clean will remove the generated files.
- The modules that will be rendered are disctated by the `developer.rst` file.
- Each module is rendered using a jinja template.
- The documentation layout is reworked.

*note*: 

- The code includes a patched version of the `autosummary` extension that does not try to generate  documentation for imported items.

### CODE REVIEW

**Comment by stefanoborini** [comment]
Since @itziakos is on vacation, I'll take this over and finish it.

**Comment by stefanoborini** [comment]
Ok, checked issue #195 means that it's in @itziakos hands as a whole. Postponing it.

**Comment by stefanoborini** [comment]
@itziakos The tests now pass. Is this finished?

**Comment by itziakos** [comment]
:+1:

**Comment by stefanoborini** [comment]
@itziakos I will solve the conflicts and merge it.

**Pull request merged**
