### PR TITLE
Remoteappdb prevents run if the database is not present

### PR DESCRIPTION
**Pull request by stefanoborini**

### CODE REVIEW

**Comment by kitchoi** [comment]
The `db_url` is managed by the `RemoteAppDBContext`, which already normalises the url, so `is_sqlitedb_url(db.url)` will always be True.  Alternatively one could have a `RemoteAppDBContext.db_exists` method that returns `True` if the database already exists.  This way it would be easy to extend `RemoteAppDBContext` for handling other database dialects (e.g. postgres).  Up to you, good to merge otherwise.

**Comment by stefanoborini** [comment]
> which already normalises the url, so is_sqlitedb_url(db.url) will always be True

not if the url is mysql://server/

**Comment by kitchoi** [comment]
> not if the url is mysql://server/
Yes I noticed that, but likewise this PR does not fix the problem for other dialects, so I understood that 'sqlite' is an existing assumption for remoteappdb, am I right?

**Comment by stefanoborini** [comment]
@kitchoi Technically, if you have a mysql database, there's pretty much nothing preventing this script to work and create all information on the mysql database, with maybe the exception of login/password information.

**Comment by kitchoi** [comment]
I believe this PR is fixing #113 right?  Does the issue exist for database dialects other than sqlite?

**Comment by stefanoborini** [comment]
If you have a different database, it will always perform the operations regardless. What you don't want, is to use the logic in place for checking sqlite databases when you passed mysql://whatever

**Comment by kitchoi** [comment]
Thanks @sbo.  After our offline discussion, I believe the issue #113 is only relevant to sqlite databases, so that is all the fix this PR needs to provide.  For other database dialects, we can rely on the admin-level control on database creation.

@sbo, it would be nice to add a comment near `if is_sqlite_url...` that mentions the file-creation behaviour on `commit`, for future reference (and for other developers).

Please merge when you're ready.  Thanks again.

**Pull request merged**
